import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/homepage/Header";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/homepage/ThemeProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSerifBengali = Noto_Serif_Bengali({
  variable: "--font-noto-serif-bengali",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const footerData = {
  logo: {
    src: "/logo.png",
    alt: "দৈনিক সকাল",
  },
  description:
    "দৈনিক সকাল হল বাংলাদেশের একটি অগ্রণী অনলাইন নিউজ পোর্টাল যা সর্বশেষ খবর, বিশ্লেষণ এবং মতামত প্রদান করে।",
  categories: [
    {
      title: "বিভাগ",
      links: [
        { label: "সর্বশেষ", href: "/category/latest" },
        { label: "জাতীয়", href: "/category/national" },
        { label: "রাজনীতি", href: "/category/politics" },
        { label: "বিশ্ব", href: "/category/world" },
        { label: "খেলা", href: "/category/sports" },
        { label: "বিনোদন", href: "/category/entertainment" },
      ],
    },
    {
      title: "দ্রুত লিঙ্ক",
      links: [
        { label: "ভিডিও", href: "/videos" },
        { label: "ফটো গ্যালারি", href: "/photo-gallery" },
        { label: "আর্কাইভ", href: "/archive" },
        { label: "বিজ্ঞাপন", href: "/advertisement" },
        { label: "আমাদের সম্পর্কে", href: "/about" },
        { label: "যোগাযোগ", href: "/contact" },
      ],
    },
  ],
  contact: {
    address: "১২৩/এ, গুলশান এভিনিউ, ঢাকা-১২১২, বাংলাদেশ",
    phone: "+৮৮০১৭১২৩৪৫৬৭৮",
    email: "info@chiritnews.com",
  },
  social: {
    facebook: "https://facebook.com",
    twitter: "https://twitter.com",
    instagram: "https://instagram.com",
    youtube: "https://youtube.com",
    linkedin: "https://linkedin.com",
  },
  quickLinks: [
    { label: "গোপনীয়তা নীতি", href: "/privacy-policy" },
    { label: "ব্যবহারের শর্তাবলী", href: "/terms-of-use" },
    { label: "কুকি নীতি", href: "/cookie-policy" },
    { label: "সাইটম্যাপ", href: "/sitemap" },
  ],
  copyright: "© ২০২৫ চিরিত সংবাদ। সর্বস্বত্ব সংরক্ষিত।",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSerifBengali.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="max-w-7xl mx-auto min-h-screen">
            <header className="sticky top-0 z-50">
              <Header />
            </header>
            <main>{children}</main>
            <footer>
              <Footer data={footerData} />
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
